/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */
import type { HttpResponseDtoTeamAnswerDtoArray } from "../../models";
import { apiV2AxiosClient } from "../../apiClient";

export const getAdminEndpoints = () => {
  /**
   * Get all answers for all teams. Accessible by admins only.
   */
  const getAllAnswers = () => {
    return apiV2AxiosClient<HttpResponseDtoTeamAnswerDtoArray>({
      url: `/answers`,
      method: "GET",
    });
  };
  return { getAllAnswers };
};
export type GetAllAnswersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAdminEndpoints>["getAllAnswers"]>>
>;
