/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * rebus-backend
 * Backend for the Rebus application, in Node.js
 * OpenAPI spec version: 2.3.0
 */
import type { HttpResponseDtoTeamAnswerDtoArray } from "../../models";
import { apiV2AxiosClient } from "../../apiClient";

export const getAdminEndpoints = () => {
  /**
   * Get all answers for all teams, long version. Accessible by admins only.
   */
  const getAllAnswers = () => {
    return apiV2AxiosClient<HttpResponseDtoTeamAnswerDtoArray>({
      url: `/answers/long`,
      method: "GET",
    });
  };
  return { getAllAnswers };
};
export type GetAllAnswersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAdminEndpoints>["getAllAnswers"]>>
>;
