import { defineConfig } from "orval";
import { InfoObject } from "openapi3-ts/oas30";

export default defineConfig({
  api_v1: {
    input: "../backend/doc/openapi-docs.json",
    output: {
      mode: "tags-split",
      target: "src/api-v1/endpoints",
      schemas: "src/api-v1/models",
      client: "axios",
      prettier: true,
      override: {
        mutator: {
          path: "src/api-v1/apiClient.ts",
          name: "apiV1AxiosClient",
        },
        // Change the default file header, remove the API version
        // to avoid changes to all generated files on every API change
        header: (info: InfoObject): string[] | string => [
          `Generated by orval`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
        ],
      },
    },
  },
  api_v2: {
    input: "../backend-v2/doc/openapi-docs.json",
    output: {
      mode: "tags-split",
      target: "src/api-v2/endpoints",
      schemas: "src/api-v2/models",
      client: "axios",
      prettier: true,
      override: {
        mutator: {
          path: "src/api-v2/apiClient.ts",
          name: "apiV2AxiosClient",
        },
        // Change the default file header, remove the API version
        // to avoid changes to all generated files on every API change
        header: (info: InfoObject): string[] | string => [
          `Generated by orval`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
        ],
      },
    },
  },
});
