/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */
import type { HttpResponseDtoTeamAnswerDto } from "../../models";
import { apiV2AxiosClient } from "../../apiClient";

export const getUserEndpoints = () => {
  /**
   * Get all answers for the current user, long version. Accessible by users only.
   */
  const getMyAnswers = () => {
    return apiV2AxiosClient<HttpResponseDtoTeamAnswerDto>({
      url: `/answers/my`,
      method: "GET",
    });
  };
  return { getMyAnswers };
};
export type GetMyAnswersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserEndpoints>["getMyAnswers"]>>
>;
