/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */

/**
 * Answer DTO.
 */
export interface AnswerDto {
  /** @nullable */
  answer: string | null;
  challengeId: number;
  /** @nullable */
  imageUrl: string | null;
  /** @nullable */
  score: number | null;
}
