/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */
import type { HttpResponseDtoChallengeDtoArray } from "./httpResponseDtoChallengeDtoArray";

export type ChallengeResponseDto = HttpResponseDtoChallengeDtoArray;
