/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */

/**
 * @nullable
 */
export type ErrorResponseDtoData =
  | (typeof ErrorResponseDtoData)[keyof typeof ErrorResponseDtoData]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorResponseDtoData = {} as const;
