/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */

/**
 */
export type ErrorResponseDtoStatus =
  (typeof ErrorResponseDtoStatus)[keyof typeof ErrorResponseDtoStatus];

export const ErrorResponseDtoStatus = {
  ERROR: "ERROR",
} as const;
