/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */
import type { ErrorResponseDtoData } from "./errorResponseDtoData";
import type { ErrorResponseDtoStatus } from "./errorResponseDtoStatus";

export interface ErrorResponseDto {
  /** @nullable */
  data: ErrorResponseDtoData;
  message: string;
  /** */
  status: ErrorResponseDtoStatus;
}
