/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * rebus-backend
 * Backend for the Rebus application, in Node.js
 * OpenAPI spec version: 2.3.0
 */

/**
 * @nullable
 */
export type ErrorResponseDtoData =
  | (typeof ErrorResponseDtoData)[keyof typeof ErrorResponseDtoData]
  | null;

export const ErrorResponseDtoData = {} as const;
