/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */

/**
 */
export type ErrorResponseDtoStatus =
  (typeof ErrorResponseDtoStatus)[keyof typeof ErrorResponseDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorResponseDtoStatus = {
  ERROR: "ERROR",
} as const;
