/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * rebus-backend
 * Backend for the Rebus application, in Node.js
 * OpenAPI spec version: 2.3.0
 */
import type { ErrorResponseDtoData } from "./errorResponseDtoData";
import type { ErrorResponseDtoStatus } from "./errorResponseDtoStatus";

export interface ErrorResponseDto {
  /** @nullable */
  data: ErrorResponseDtoData;
  message: string;
  /** */
  status: ErrorResponseDtoStatus;
}
