/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * rebus-backend
 * Backend for the Rebus application, in Node.js
 * OpenAPI spec version: 2.3.0
 */

/**
 */
export type ErrorResponseDtoStatus =
  (typeof ErrorResponseDtoStatus)[keyof typeof ErrorResponseDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorResponseDtoStatus = {
  ERROR: "ERROR",
} as const;
