/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */

/**
 * @nullable
 */
export type ErrorResponseDtoData =
  | (typeof ErrorResponseDtoData)[keyof typeof ErrorResponseDtoData]
  | null;

export const ErrorResponseDtoData = {} as const;
