/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * rebus-backend
 * Backend for the Rebus application, in Node.js
 * OpenAPI spec version: 2.3.0
 */
import type { TeamAnswerDto } from "./teamAnswerDto";
import type { HttpResponseDtoTeamAnswerDtoArrayStatus } from "./httpResponseDtoTeamAnswerDtoArrayStatus";

/**
 * Generic HTTP response body.
 */
export interface HttpResponseDtoTeamAnswerDtoArray {
  data: TeamAnswerDto[];
  message: string;
  status: HttpResponseDtoTeamAnswerDtoArrayStatus;
}
