/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */

export type HttpResponseDtoTeamAnswerDtoArrayStatus =
  (typeof HttpResponseDtoTeamAnswerDtoArrayStatus)[keyof typeof HttpResponseDtoTeamAnswerDtoArrayStatus];

export const HttpResponseDtoTeamAnswerDtoArrayStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
