/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */

export type HttpResponseDtoChallengeDtoArrayStatus =
  (typeof HttpResponseDtoChallengeDtoArrayStatus)[keyof typeof HttpResponseDtoChallengeDtoArrayStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HttpResponseDtoChallengeDtoArrayStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
