/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */

export type HttpResponseDtoStringStatus =
  (typeof HttpResponseDtoStringStatus)[keyof typeof HttpResponseDtoStringStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HttpResponseDtoStringStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
