/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * rebus-backend
 * Backend for the Rebus application, in Node.js
 * OpenAPI spec version: 2.3.0
 */

export type HttpResponseDtoTeamAnswerDtoArrayStatus =
  (typeof HttpResponseDtoTeamAnswerDtoArrayStatus)[keyof typeof HttpResponseDtoTeamAnswerDtoArrayStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HttpResponseDtoTeamAnswerDtoArrayStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
