/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */

export type HttpResponseDtoTeamAnswerDtoArrayStatus =
  (typeof HttpResponseDtoTeamAnswerDtoArrayStatus)[keyof typeof HttpResponseDtoTeamAnswerDtoArrayStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HttpResponseDtoTeamAnswerDtoArrayStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
