/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */
import type { ChallengeDto } from "./challengeDto";
import type { HttpResponseDtoChallengeDtoArrayStatus } from "./httpResponseDtoChallengeDtoArrayStatus";

/**
 * Generic HTTP response body.
 */
export interface HttpResponseDtoChallengeDtoArray {
  data: ChallengeDto[];
  message: string;
  status: HttpResponseDtoChallengeDtoArrayStatus;
}
