/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */
import type { TeamAnswerDto } from "./teamAnswerDto";
import type { HttpResponseDtoTeamAnswerDtoStatus } from "./httpResponseDtoTeamAnswerDtoStatus";

/**
 * Generic HTTP response body.
 */
export interface HttpResponseDtoTeamAnswerDto {
  data: TeamAnswerDto;
  message: string;
  status: HttpResponseDtoTeamAnswerDtoStatus;
}
