/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */
import type { HttpResponseDtoTeamAnswerDtoArray } from "./httpResponseDtoTeamAnswerDtoArray";

export type TeamAnswerResponseDto = HttpResponseDtoTeamAnswerDtoArray;
