/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */
import type { HttpResponseDtoTeamAnswerDtoArray } from "./httpResponseDtoTeamAnswerDtoArray";

/**
 * Answers for all teams.
 */
export type TeamListAnswerResponseDto = HttpResponseDtoTeamAnswerDtoArray;
