/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */
import type { HttpResponseDtoTeamAnswerDto } from "./httpResponseDtoTeamAnswerDto";

/**
 * Answers for one team.
 */
export type TeamAnswerResponseDto = HttpResponseDtoTeamAnswerDto;
