/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */
import type { AnswerDto } from "./answerDto";

/**
 * Team answer DTO.
 */
export interface TeamAnswerDto {
  answers: AnswerDto[];
  teamId: number;
}
