/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Rebus backend
 * OpenAPI spec version: 2.1.0
 */
import type {
  HttpResponseDtoListShortTeamAnswerDto,
  HttpResponseDtoListTeamDto,
  HttpResponseDtoString,
  SingleScoreDto,
} from "../../models";
import { apiV1AxiosClient } from "../../apiClient";

export const getAdminEndpoints = () => {
  /**
   * @summary Get all answers
   */
  const getAllAnswersShortened = () => {
    return apiV1AxiosClient<HttpResponseDtoListShortTeamAnswerDto>({
      url: `/answers`,
      method: "GET",
    });
  };
  /**
   * @summary Set score for a specific team, specific challenge
   */
  const setScore = (
    challengeId: number,
    userId: number,
    singleScoreDto: SingleScoreDto
  ) => {
    return apiV1AxiosClient<HttpResponseDtoString>({
      url: `/score/${challengeId}/${userId}`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: singleScoreDto,
    });
  };
  /**
   * @summary Get all teams
   */
  const getAllTeams = () => {
    return apiV1AxiosClient<HttpResponseDtoListTeamDto>({
      url: `/teams`,
      method: "GET",
    });
  };
  return { getAllAnswersShortened, setScore, getAllTeams };
};
export type GetAllAnswersShortenedResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAdminEndpoints>["getAllAnswersShortened"]>
  >
>;
export type SetScoreResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAdminEndpoints>["setScore"]>>
>;
export type GetAllTeamsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAdminEndpoints>["getAllTeams"]>>
>;
