/**
 * Generated by orval
 * Do not edit manually.
 * rebus-backend
 */
import type { HttpResponseDtoChallengeDtoArray } from "../../models";
import { apiV2AxiosClient } from "../../apiClient";

export const getPublicEndpoints = () => {
  const getChallenges = () => {
    return apiV2AxiosClient<HttpResponseDtoChallengeDtoArray>({
      url: `/challenges`,
      method: "GET",
    });
  };
  return { getChallenges };
};
export type GetChallengesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPublicEndpoints>["getChallenges"]>>
>;
