/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */

/**
 * Response of a successful authentication
 */
export interface AuthenticationResponse {
  /** JWT token */
  jwt: string;
}
