/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Rebus backend
 * OpenAPI spec version: 2.0.0
 */

/**
 * Data that the user sends in the login request
 */
export interface AuthenticationRequest {
  /** The PIN code of the user (team) */
  pin: string;
}
