/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */

/**
 * Data that the user sends in the login request
 */
export interface AuthenticationRequest {
  /** The PIN code of the user (team) */
  pin: string;
}
