/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Rebus backend
 * OpenAPI spec version: 3.0.0
 */

/**
 * Response of a successful authentication
 */
export interface AuthenticationResponse {
  /** JWT token */
  jwt: string;
}
