/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Rebus backend
 * OpenAPI spec version: 2.0.0
 */

/**
 * Challenge data
 */
export interface ChallengeDto {
  /** ID of the challenge */
  id: number;
  /** Max score for this challenge */
  maxScore?: number;
  /** The question of the challenge */
  question: string;
}
