/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */

/**
 * Challenge data
 */
export interface ChallengeDto {
  /** ID of the challenge */
  id: number;
  /** Max score for this challenge */
  maxScore?: number;
  /** The question of the challenge */
  question: string;
}
