/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Rebus backend
 * OpenAPI spec version: 2.2.0
 */

/**
 * Response status: success or error
 */
export type HttpResponseDtoTeamAnswerDtoStatus =
  (typeof HttpResponseDtoTeamAnswerDtoStatus)[keyof typeof HttpResponseDtoTeamAnswerDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HttpResponseDtoTeamAnswerDtoStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
