/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Rebus backend
 * OpenAPI spec version: 2.1.0
 */

/**
 * Response status: success or error
 */
export type HttpResponseDtoAuthenticationResponseStatus =
  (typeof HttpResponseDtoAuthenticationResponseStatus)[keyof typeof HttpResponseDtoAuthenticationResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HttpResponseDtoAuthenticationResponseStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
