/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Rebus backend
 * OpenAPI spec version: 4.0.0
 */

/**
 * Response status: success or error
 */
export type HttpResponseDtoListChallengeDtoStatus =
  (typeof HttpResponseDtoListChallengeDtoStatus)[keyof typeof HttpResponseDtoListChallengeDtoStatus];

export const HttpResponseDtoListChallengeDtoStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
