/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */

/**
 * Response status: success or error
 */
export type HttpResponseDtoTeamAnswerDtoStatus =
  (typeof HttpResponseDtoTeamAnswerDtoStatus)[keyof typeof HttpResponseDtoTeamAnswerDtoStatus];

export const HttpResponseDtoTeamAnswerDtoStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
