/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Rebus backend
 * OpenAPI spec version: 2.2.0
 */
import type { TeamDto } from "./teamDto";
import type { HttpResponseDtoListTeamDtoStatus } from "./httpResponseDtoListTeamDtoStatus";

/**
 * Response from the server
 */
export interface HttpResponseDtoListTeamDto {
  /** The data that the server will send in the response, can be null */
  data?: TeamDto[];
  /** A message explaining the response, in case of errors */
  message?: string;
  /** Response status: success or error */
  status?: HttpResponseDtoListTeamDtoStatus;
}
