/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */
import type { HttpResponseDtoStringStatus } from "./httpResponseDtoStringStatus";

/**
 * Response from the server
 */
export interface HttpResponseDtoString {
  /** The data that the server will send in the response, can be null */
  data?: string;
  /** A message explaining the response, in case of errors */
  message?: string;
  /** Response status: success or error */
  status?: HttpResponseDtoStringStatus;
}
