/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */

/**
 * Response status: success or error
 */
export type HttpResponseDtoListTeamAnswerDtoStatus =
  (typeof HttpResponseDtoListTeamAnswerDtoStatus)[keyof typeof HttpResponseDtoListTeamAnswerDtoStatus];

export const HttpResponseDtoListTeamAnswerDtoStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
