/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */

/**
 * Response status: success or error
 */
export type HttpResponseDtoListChallengeDtoStatus =
  (typeof HttpResponseDtoListChallengeDtoStatus)[keyof typeof HttpResponseDtoListChallengeDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HttpResponseDtoListChallengeDtoStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
