/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Rebus backend
 * OpenAPI spec version: 3.0.0
 */

/**
 * Response status: success or error
 */
export type HttpResponseDtoStringStatus =
  (typeof HttpResponseDtoStringStatus)[keyof typeof HttpResponseDtoStringStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HttpResponseDtoStringStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
