/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */

/**
 * Response status: success or error
 */
export type HttpResponseDtoStringStatus =
  (typeof HttpResponseDtoStringStatus)[keyof typeof HttpResponseDtoStringStatus];

export const HttpResponseDtoStringStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
