/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Rebus backend
 * OpenAPI spec version: 4.0.0
 */

/**
 * Response status: success or error
 */
export type HttpResponseDtoListTeamAnswerDtoStatus =
  (typeof HttpResponseDtoListTeamAnswerDtoStatus)[keyof typeof HttpResponseDtoListTeamAnswerDtoStatus];

export const HttpResponseDtoListTeamAnswerDtoStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
