/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */

/**
 * Response status: success or error
 */
export type HttpResponseDtoListTeamDtoStatus =
  (typeof HttpResponseDtoListTeamDtoStatus)[keyof typeof HttpResponseDtoListTeamDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HttpResponseDtoListTeamDtoStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
