/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */
import type { ChallengeDto } from "./challengeDto";
import type { HttpResponseDtoListChallengeDtoStatus } from "./httpResponseDtoListChallengeDtoStatus";

/**
 * Response from the server
 */
export interface HttpResponseDtoListChallengeDto {
  /** The data that the server will send in the response, can be null */
  data?: ChallengeDto[];
  /** A message explaining the response, in case of errors */
  message?: string;
  /** Response status: success or error */
  status?: HttpResponseDtoListChallengeDtoStatus;
}
