/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */

/**
 * Response status: success or error
 */
export type HttpResponseDtoAuthenticationResponseStatus =
  (typeof HttpResponseDtoAuthenticationResponseStatus)[keyof typeof HttpResponseDtoAuthenticationResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HttpResponseDtoAuthenticationResponseStatus = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
