/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */
import type { AuthenticationResponse } from "./authenticationResponse";
import type { HttpResponseDtoAuthenticationResponseStatus } from "./httpResponseDtoAuthenticationResponseStatus";

/**
 * Response from the server
 */
export interface HttpResponseDtoAuthenticationResponse {
  data?: AuthenticationResponse;
  /** A message explaining the response, in case of errors */
  message?: string;
  /** Response status: success or error */
  status?: HttpResponseDtoAuthenticationResponseStatus;
}
