/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */

/**
 * Our team's answer for one specific challenge
 */
export interface MyAnswerDto {
  /** The answer text */
  answer?: string;
  /** ID of the challenge */
  challengeId: number;
}
