/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Rebus backend
 * OpenAPI spec version: 3.0.0
 */

/**
 * Our team's answer for one specific challenge
 */
export interface MyAnswerDto {
  /** The answer text */
  answer?: string;
  /** ID of the challenge */
  challengeId: number;
}
