/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Rebus backend
 * OpenAPI spec version: 2.1.0
 */

/**
 * Team answers, in a short form
 */
export interface ShortTeamAnswerDto {
  /** List of answers to all challenges for the team */
  answers: string[];
  /** Scores for each answer */
  scores: number[];
  /** ID of the team */
  teamId: number;
}
