/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */

/**
 * A team's answer for one specific challenge
 */
export interface SimpleAnswerDto {
  /** The answer text */
  answer?: string;
}
