/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */

/**
 * A single score
 */
export interface SingleScoreDto {
  /** The score for the answer, can be null */
  score?: number;
}
