/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Rebus backend
 * OpenAPI spec version: 2.2.0
 */

/**
 * A single score
 */
export interface SingleScoreDto {
  /** The score for the answer, can be null */
  score?: number;
}
