/**
 * Generated by orval
 * Do not edit manually.
 * Rebus backend
 */

/**
 * The data that the server will send in the response, can be null
 */
export interface TeamDto {
  /** ID of the team */
  id: number;
  /** Name of the team */
  name: string;
}
