name: Run backend-v2 tests

on:
  push:
    branches: [ "master" ]
    paths: [ "backend-v2/**" ]
  pull_request:
    branches: [ "master" ]
  # Allow to run the workflow manually on GitHub website
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-v2
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: npm run test:ci
